function loadSounds()
mus_title = snd.newSource("music/MUS_TITLE.mp3", "stream")
sfx_talk_f =  snd.newSource("sfx/SFX_TALK_F.wav", "static")
sfx_ttlSelect = snd.newSource("sfx/SFX_TTLSelect.wav", "static")
sfx_optionSelect = snd.newSource("sfx/SFX_OptionSelect.wav", "static")
sfx_optionChange = snd.newSource("sfx/SFX_OptionChange.wav", "static")
sfx_menuSelect =  snd.newSource("sfx/SFX_Menu_Select.wav", "static")
sfx_menuBack =  snd.newSource("sfx/SFX_Menu_Back.wav", "static")
sfx_NOISE = snd.newSource("sfx/SFX_Noise.wav", "static")
sfx_options = snd.newSource("sfx/SFX_OptionChange.wav", "static")
end
